clear
close all

today = datestr(date(), 'yyyymmdd');
experiments = [3];
AXIS = [    0.3979    0.5432   -1.2014   -0.9592]*1e6;
if any(experiments == 1) % exp 1: setup project ISMIP6 temperature to the domain, with shear margin weakening {{{
	steps = [1,2];
	md = runme('steps', steps, 'damageType', 0);
end %}}}
if any(experiments == 2) % exp 2: inversion B{{{
	steps = [3];
	costcoeffs = [700, 0.05, 2e-16];
	AXIS = [    0.4190    0.5400   -1.1756   -0.9673]*1e6;
	md = runme('steps', steps, ...
		'damageType', 0,...
		'cost coefficients', costcoeffs);
end %}}}
if any(experiments == 3) % exp 3: inversion Budd{{{
	steps = [4];
	costcoeffs = [100, 0.03, 5e-9];
	AXIS = [    0.4190    0.5400   -1.1756   -0.9673]*1e6;
	md = runme('steps', steps, ...
		'damageType', 0,...
		'rerun inversion', 0, ...
		'calving', 'Obs', ...
		'friction', 'Budd', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.inversion.vel_obs, 'caxis', [-300,300], 'title', 'Vel-Velobs', ...
		'axis#all',AXIS,...
		'mask#all',md.mask.ice_levelset<0,...
		'data', log(md.friction.coefficient)./log(10), 'title', 'log_{10}(coefficient)',...
		'data', md.results.StressbalanceSolution.Vel, 'caxis#3,4', [0,2e3], 'title', 'Vel', ...
		'data', md.inversion.vel_obs, 'title', 'Obs')
end %}}}
if any(experiments == 4) % exp 4: inversion B again{{{
	steps = [5];
	costcoeffs = [700, 15, 2e-16];
	AXIS = [    0.4190    0.5400   -1.1756   -0.9673]*1e6;
	md = runme('steps', steps, ...
		'damageType', 0,...
		'cost coefficients', costcoeffs);
end %}}}


return
if any(experiments == 3) % exp 3: rerun inversion Budd{{{
	steps = [3];
	costcoeffs = [2500, 0.2, 4e-8];
	md = runme('steps', steps, ...
		'damageType', 1,...
		'rerun inversion', 1, ...
		'calving', 'Obs', ...
		'friction', 'Budd', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.inversion.vel_obs, 'caxis', [-1e3,1e3], 'title', 'Vel-Velobs', ...
		'axis#all', AXIS, ...
		'mask#all', md.mask.ice_levelset<0,...
		'data', md.results.StressbalanceSolution.Vel, 'caxis', [0,12e3], 'title', 'Vel', ...
		'data', md.results.StressbalanceSolution.Gradient1, 'title', 'Gradient', ...
		'data', log(md.friction.coefficient)./log(10), 'title', 'log_{10}(coefficient)');
end %}}}
if any(experiments == 4) % exp 4: inversion Schoof{{{
	steps = [5];
	costcoeffs = [7000, 1.0, 0.5e-9];
	md = runme('steps', steps, ...
		'damageType', 3,...
		'rerun inversion', 0, ...
		'calving', 'Obs', ...
		'use Weertman', 1,...
		'friction', 'Schoof', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.initialization.vel, 'caxis', [-1e3,1e3], 'title', 'Vel-Velobs', ...
		'axis#all', AXIS, ...
		'data', md.results.StressbalanceSolution.Vel, 'caxis', [0,12e3], 'title', 'Vel', ...
		'data', md.results.StressbalanceSolution.Gradient1, 'title', 'Gradient', ...
		'data', log(md.friction.C)./log(10), 'title', 'log_{10}(coefficient)');
end %}}}
if any(experiments == 5) % exp 5: rerun inversion Schoof{{{
	steps = [5];
	costcoeffs = [7000, 1.0, 0.5e-9];
	md = runme('steps', steps, ...
		'damageType', 3,...
		'rerun inversion', 1, ...
		'calving', 'Obs', ...
		'friction', 'Schoof', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.initialization.vel, 'caxis', [-1e3,1e3], 'title', 'Vel-Velobs', ...
		'axis#all', AXIS, ...
		'data', md.results.StressbalanceSolution.Vel, 'caxis', [0,12e3], 'title', 'Vel', ...
		'data', md.results.StressbalanceSolution.Gradient1, 'title', 'Gradient', ...
		'data', log(md.friction.C)./log(10), 'title', 'log_{10}(coefficient)');
end %}}}
if any(experiments == 6) % exp 6: inversion Weertman{{{
	steps = [4];
	costcoeffs = [7000, 0.25, 4.5e-10];
	md = runme('steps', steps, ...
		'damageType', 3,...
		'calving', 'Obs', ...
		'rerun inversion', 0, ...
		'friction', 'Weertman', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.initialization.vel, 'caxis', [-1e3,1e3], 'title', 'Vel-Velobs', ...
		'axis#all', AXIS, ...
		'data', md.results.StressbalanceSolution.Vel, 'caxis', [0,12e3], 'title', 'Vel', ...
		'data', md.results.StressbalanceSolution.Gradient1, 'title', 'Gradient', ...
		'data', log(md.friction.C)./log(10), 'title', 'log_{10}(C)');
end %}}}
if any(experiments == 7) % exp 7: rerun inversion Weertman{{{
	steps = [4];
	costcoeffs = [7000, 0.5, 4.5e-10];
	md = runme('steps', steps, ...
		'damageType', 3,...
		'calving', 'Obs', ...
		'rerun inversion', 1, ...
		'friction', 'Weertman', ...
		'cost coefficients', costcoeffs);
	plotmodel(md, 'data', md.results.StressbalanceSolution.Vel-md.initialization.vel, 'caxis', [-1e3,1e3], 'title', 'Vel-Velobs', ...
		'axis#all', AXIS, ...
		'data', md.results.StressbalanceSolution.Vel, 'caxis', [0,12e3], 'title', 'Vel', ...
		'data', md.results.StressbalanceSolution.Gradient1, 'title', 'Gradient', ...
		'data', log(md.friction.C)./log(10), 'title', 'log_{10}(C)');
end %}}}
if any(experiments == 8) % exp 8: set ice masks{{{
	steps = [7];
	frictions = {'Budd', 'Schoof', 'Weertman'};
	for i = 1:length(frictions)
		md = runme('steps', steps, ...
			'startTime',2007,...
			'damageType', 3,...
			'friction', frictions{i});
	end
end %}}}
if any(experiments == 9) % exp 9: set SMB{{{
	steps = [8]; % test with the MAR data sets
	frictions = {'Budd', 'Schoof', 'Weertman'};
	SMB = {'MAR_6k'};
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			md = runme('steps', steps, ...
				'startTime',2007,...
				'damageType', 3,...
				'smb model', SMB{j}, ...
				'friction', frictions{i});
		end
	end
end %}}}
if any(experiments == 10) % exp 10: run transient{{{
	steps = [9]; 
	frictions = {'Budd', 'Schoof', 'Weertman'};
	SMB = {'MAR_6k'};
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			savePath = [today, '_Jakobshavn_',SMB{j},'_', frictions{i}];
			md = runme('steps', steps, ...
				'startTime',2007,...
				'cluster name', 'frontera',...
				'damageType', 3,...
				'smb model', SMB{j}, ...
				'friction', frictions{i}, ...
				'savePath', [savePath]);
		end
	end
end %}}}

%--------------- Run from 1958
if any(experiments == 11) % exp 11: set ice masks back to 1958{{{
	steps = [6];
	frictions = {'Schoof'};
	%frictions = {'Budd', 'Schoof', 'Weertman'};
	for i = 1:length(frictions)
		md = runme('steps', steps, ...
			'startTime',1958,...
			'damageType', 3,...
			'friction', frictions{i});
	end
end %}}}
if any(experiments == 12) % exp 12: set SMB{{{
	steps = [8]; % test with the MAR data sets
	frictions = {'Schoof'};
	%frictions = {'Budd', 'Schoof', 'Weertman'};
	SMB = {'RACMO','MAR_6k'};
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			md = runme('steps', steps, ...
				'startTime',1958,...
				'damageType', 3,...
				'smb model', SMB{j}, ...
				'friction', frictions{i});
		end
	end
end %}}}
if any(experiments == 13) % exp 13: run transient{{{
	steps = [9]; 
	frictions = {'Budd', 'Schoof', 'Weertman'};
	SMB = {'RACMO', 'MAR_6k'};
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			savePath = [today, '_JakobshavnFrom1958_',SMB{j},'_', frictions{i}];
			md = runme('steps', steps, ...
				'startTime',1958,...
				'cluster name', 'andes',...
				'jobTime', 10,...
				'damageType', 3,...
				'smb model', SMB{j}, ...
				'friction', frictions{i}, ...
				'savePath', [savePath]);
		end
	end
end %}}}

%--------------- Run yearly, quaterly, monthly fronts
frictions = {'Weertman'};
SMB = {'RACMO'};
if any(experiments == 21) % exp 21: set ice masks{{{
	steps = [7];
	for i = 1:length(frictions)
		md = runme('steps', steps, ...
			'startTime',2007,...
			'damageType', 3,...
			'friction', frictions{i});
	end
end %}}}
if any(experiments == 22) % exp 22: set SMB{{{
	steps = [8]; % test with the MAR data sets
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			md = runme('steps', steps, ...
				'startTime',2007,...
				'damageType', 3,...
				'smb model', SMB{j}, ...
				'friction', frictions{i});
		end
	end
end %}}}
if any(experiments == 23) % exp 23: run yearly front transient{{{
	steps = [9]; 
	monthfront = [1:12];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(monthfront)
				savePath = [today, '_Jakobshavn_yearly_', num2str(monthfront(k)), '_', SMB{j}, '_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',2007,...
					'cluster name', 'frontera',...
					'jobTime', 5,...
					'damageType', 3,...
					'month',monthfront(k),...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}

return
%--------------- test Schoof with different friction C before 2007 
if any(experiments == 21) % exp 21: run transient{{{
	steps = [6, 8, 9]; 
	frictions = {'Budd', 'Weertman'};
	SMB = {'RACMO', 'MAR_6k'};
	C_before = [1e-2, 1e-1];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(C_before)
				savePath = [today, '_Jakobshavn_C', num2str(C_before(k)), '_From1958_',SMB{j},'_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',1958,...
					'cluster name', 'andes',...
					'jobTime', 10,...
					'damageType', 3,...
					'C before 2007', C_before(k),...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}
if any(experiments == 22) % exp 22: prepare run transient{{{
	steps = [6, 8]; 
	frictions = {'Schoof', 'Budd', 'Weertman'};
	SMB = {'RACMO', 'MAR_6k'};
	for i = 1:length(frictions)
		for j = 1:length(SMB)
				md = runme('steps', steps, ...
					'damageType', 3,...
					'startTime',1958,...
					'smb model', SMB{j}, ...
					'friction', frictions{i});
		end
	end
end %}}}
if any(experiments == 23) % exp 23: run transient Weertman{{{
	steps = [9]; 
	frictions = {'Weertman'};
	SMB = {'RACMO'};
	C_before = [10, 100, 500];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(C_before)
				savePath = [today, '_Jakobshavn_C', num2str(C_before(k)), '_From1958_',SMB{j},'_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',1958,...
					'cluster name', 'andes',...
					'jobTime', 10,...
					'damageType', 3,...
					'C before 2007', C_before(k),...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}
if any(experiments == 24) % exp 24: run transient Budd{{{
	steps = [9]; 
	frictions = {'Budd'};
	SMB = {'RACMO'};
	C_before = [15, 20];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(C_before)
				savePath = [today, '_Jakobshavn_C', num2str(C_before(k)), '_From1958_',SMB{j},'_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',1958,...
					'cluster name', 'andes',...
					'jobTime', 10,...
					'damageType', 3,...
					'C before 2007', C_before(k),...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}
if any(experiments == 25) % exp 25: run transient Schoof{{{
	steps = [9]; 
	frictions = {'Schoof'};
	SMB = {'RACMO'};
	C_before = [10, 100, 500];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(C_before)
				savePath = [today, '_Jakobshavn_Weertman_C', num2str(C_before(k)), '_From1958_',SMB{j},'_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',1958,...
					'cluster name', 'andes',...
					'jobTime', 10,...
					'damageType', 3,...
					'Cmax before 2007', 1e10,...
					'apply Weertman', 1,...
					'C before 2007', C_before(k),...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}
if any(experiments == 26) % exp 26: run transient Schoof cmax test{{{
	steps = [9]; 
	frictions = {'Schoof'};
	SMB = {'RACMO'};
	Cmax_before = [1e-2, 0.1];
	for i = 1:length(frictions)
		for j = 1:length(SMB)
			for k = 1:length(Cmax_before)
				savePath = [today, '_Jakobshavn_Cmax', num2str(Cmax_before(k)), '_From1958_',SMB{j},'_', frictions{i}];
				md = runme('steps', steps, ...
					'startTime',1958,...
					'jobTime', 10,...
					'damageType', 3,...
					'cluster name', 'andes',...
					'Cmax before 2007', Cmax_before(k),...
					'C before 2007', 1e-2,...
					'smb model', SMB{j}, ...
					'friction', frictions{i}, ...
					'savePath', [savePath]);
			end
		end
	end
end %}}}

%--------------- prepare the mesh for GNSS
if any(experiments == 1001) % exp 1001: save mesh to a txt file{{{
   steps = [10];
   md = runme('steps', steps);
end %}}}
