function [folderList, nameList] = getFolderList(Id)
	%getFolderList - return the working folders
	%
	% Author: Cheng Gong
	% Last modified: 2026-07-24
	if nargin < 1
		Id = 0;
	end
	if Id == 0  % Latest test{{{
		folderList = {...
			'20260803_NEGIS_MAR_Budd/',...
			'20260803_NEGIS_MAR_Weertman/',...
			'20260803_NEGIS_MAR_Schoof/',...
			'20260803_NEGIS_RACMO_Budd/',...
			'20260803_NEGIS_RACMO_Weertman/',...
			'20260803_NEGIS_RACMO_Schoof/',...
			};
		nameList = {...
			'MAR, Budd',...
			'MAR, Weertman',...
			'MAR, Schoof',...
			'RACMO, Budd',...
			'RACMO, Weertman',...
			'RACMO, Schoof',...
			}; %}}}
	elseif Id == -1 % -1: empty {{{
		folderList = {
		};
		nameList = {
		}; %}}}
	end
end
